---
- hosts: apache
  remote_user: root
  vars:
    http_port: 80
    max_client: 300 
  tasks:
  - name: starting apache web server service 
    service:
      name: httpd
      state: started 
      enabled: yes
  - name: permit selinux
    lineinfile: dest=/etc/selinux/config
                regexp='^SELINUX='
                line='SELINUX=permissive'
                state=present

  - name: iptables flush
    command: iptables -F
