---
- name: Deploy HAproxy
- name: enable repos
  template:
    src: packages.repo.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: install HAProxy
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
     - httpie
     - haproxy

- name: start HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart HAproxy
